### ISSUE TITLE
panic when stream with more than one token ends with any white space

### ISSUE THREAD

**Issue by n-peugnet** [bzick/tokenizer#26]
Hi, This code:

```go
import (
	"bytes"

	"github.com/bzick/tokenizer"
)

func main() {
	// configure tokenizer
	parser := tokenizer.New()

	// create tokens' stream
	stream := parser.ParseStream(bytes.NewBufferString("test coucou\n"), 4096)
	defer stream.Close()

	// iterate over each token
	for stream.IsValid() {
		// do something...
		stream.GoNext()
	}
}
```

Produces this panic:

```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/bzick/tokenizer.(*parsing).parse(0xc000196340)
	/home/nicolas/go/pkg/mod/github.com/bzick/tokenizer@v1.4.6/parser.go:158 +0x2db
github.com/bzick/tokenizer.(*Stream).GoNext(0xc0001a4120)
	/home/nicolas/go/pkg/mod/github.com/bzick/tokenizer@v1.4.6/stream.go:103 +0x6f
main.main()
	/home/nicolas/testmodule/main.go:21 +0x1d4
exit status 2
```

Removing either the `\n` or the `coucou` part of the string makes it work without crashing.

**Comment by bzick** [comment]
Thank you! v.1.4.7
